<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");
header("Content-Type: application/json; charset=UTF-8");

// Handle preflight requests
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
  http_response_code(200);
  exit;
}

if ($_SERVER["REQUEST_METHOD"] === "POST") {

  // Recibir datos JSON desde React (fetch)
  $json = file_get_contents('php://input');
  $data = json_decode($json, true);

  // Identificar la fuente (Contact Form vs Quote Calculator)
  $source = strip_tags(trim($data["source"] ?? 'Contact Form'));

  // Sanitizar datos comunes
  $nombre = strip_tags(trim($data["name"] ?? $data["customerName"] ?? ''));
  $telefono = strip_tags(trim($data["phone"] ?? $data["customerPhone"] ?? ''));
  $email = filter_var(trim($data["email"] ?? $data["customerEmail"] ?? ''), FILTER_SANITIZE_EMAIL);

  // Datos específicos del formulario
  $servicio = strip_tags(trim($data["service"] ?? $data["serviceType"] ?? ''));
  $metros = strip_tags(trim($data["sqft"] ?? ''));
  $fecha = strip_tags(trim($data["date"] ?? 'Not specified'));
  $mensaje = strip_tags(trim($data["message"] ?? ''));

  // Datos específicos del cotizador
  $totalPrice = strip_tags(trim($data["totalPrice"] ?? ''));
  $pdfBase64 = $data["pdfAttachment"] ?? null;

  // Validar requeridos
  if (empty($nombre) || empty($telefono) || empty($email) || empty($servicio)) {
    http_response_code(400);
    echo json_encode(["status" => "error", "message" => "Please complete all required fields."]);
    exit;
  }

  if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    http_response_code(400);
    echo json_encode(["status" => "error", "message" => "Invalid email address."]);
    exit;
  }

  // Configuración del correo
  $adminEmails = "jorgegonzalezmejia@gmail.com";

  // Si es una cotización, enviar también copia al cliente
  $destinatarios = ($source === 'Quote Calculator') ? "$adminEmails, $email" : $adminEmails;

  $asunto = ($source === 'Quote Calculator')
    ? "Your Angels Cleaning Services Quote - $nombre"
    : "New Web Request: $servicio - $nombre";

  // Plantilla HTML profesional del correo
  $htmlContent = "
    <html>
    <head>
      <style>
        body { font-family: 'Arial', sans-serif; color: #333; line-height: 1.6; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
        .header { background-color: #003E7C; color: #fff; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
        h1 { margin: 0; font-size: 24px; }
        .content { padding: 20px; background-color: #f9f9f9; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        .label { font-weight: bold; width: 35%; color: #003E7C; }
        .footer { text-align: center; margin-top: 20px; font-size: 12px; color: #888; }
        .price-badge { display: inline-block; background-color: #0097DB; color: white; padding: 10px 20px; border-radius: 5px; font-size: 20px; font-weight: bold; margin-top: 15px; }
      </style>
    </head>
    <body>
      <div class='container'>
        <div class='header'>
          <h1>" . ($source === 'Quote Calculator' ? "New Cleaning Estimate" : "New Service Request") . "</h1>
          <p>Angels Cleaning Services</p>
        </div>
        <div class='content'>
          <p>Hello,</p>
          <p>Here are the details generated from the website ($source):</p>
          <table>
            <tr><td class='label'>Client:</td><td>$nombre</td></tr>
            <tr><td class='label'>Phone:</td><td>$telefono</td></tr>
            <tr><td class='label'>Email:</td><td>$email</td></tr>
            <tr><td class='label'>Service Type:</td><td>$servicio</td></tr>
            <tr><td class='label'>Approximate Size:</td><td>$metros sqft</td></tr>
            <tr><td class='label'>Preferred Date:</td><td>$fecha</td></tr>";

  if ($mensaje) {
    $htmlContent .= "<tr><td class='label'>Details:</td><td>$mensaje</td></tr>";
  }

  $htmlContent .= "
          </table>";

  if ($source === 'Quote Calculator') {
    $htmlContent .= "<div style='text-align: center;'><div class='price-badge'>Estimated Total: $$totalPrice USD</div><p style='margin-top:15px'>Find the detailed PDF attached to this email.</p></div>";
  }

  $htmlContent .= "
        </div>
        <div class='footer'>
          <p>This message was automatically generated by Angels Cleaning App.</p>
        </div>
      </div>
    </body>
    </html>
    ";

  // Generar un límite único para el correo multipart
  $boundary = md5(time());

  // Cabeceras principales
  $headers = "From: Angels Cleaning <noreply@angelscleaningservices.com>\r\n";
  $headers .= "Reply-To: $email\r\n";
  $headers .= "MIME-Version: 1.0\r\n";

  if ($pdfBase64) {
    // Enviar Multipart (HTML + Archivo Adjunto)
    $headers .= "Content-Type: multipart/mixed; boundary=\"$boundary\"\r\n";

    // Cuerpo del mensaje multipart
    $message = "--$boundary\r\n";
    $message .= "Content-Type: text/html; charset=UTF-8\r\n";
    $message .= "Content-Transfer-Encoding: 7bit\r\n\r\n";
    $message .= $htmlContent . "\r\n\r\n";

    // Adjuntar PDF
    $message .= "--$boundary\r\n";
    $message .= "Content-Type: application/pdf; name=\"Angels_Cleaning_Quote.pdf\"\r\n";
    $message .= "Content-Transfer-Encoding: base64\r\n";
    $message .= "Content-Disposition: attachment; filename=\"Angels_Cleaning_Quote.pdf\"\r\n\r\n";

    // Insertar el base64 respetando los saltos de línea requeridos por el estándar MIME
    $message .= chunk_split($pdfBase64) . "\r\n\r\n";
    $message .= "--$boundary--";

  } else {
    // Enviar solo HTML (Comportamiento Original)
    $headers .= "Content-type:text/html;charset=UTF-8\r\n";
    $message = $htmlContent;
  }

  // Intentar Enviar
  if (mail($destinatarios, $asunto, $message, $headers)) {
    http_response_code(200);
    echo json_encode(["status" => "success", "message" => "Request sent successfully."]);
  } else {
    http_response_code(500);
    echo json_encode(["status" => "error", "message" => "Failed to send email on server."]);
  }

} else {
  http_response_code(403);
  echo json_encode(["status" => "error", "message" => "Invalid request method."]);
}
?>